### ISSUE TITLE
usb-200 two channel synchronous sampling

### ISSUE THREAD

**Issue by mzy2240** [mccdaq/uldaq#12]
Updates: It seems like it is impossible to use usb200 for synchronous sampling. However when I checked the synchronous DAQ USB-1608FS-Plus, I still did not find any configs related to synchronous sampling using python. Any info on that will be really appreciated!

Howdy! Is it possible to do two channel synchronous sampling using usb-200? Didn't find any relevant document yet. Thanks!!

**Comment by sbazaz** [comment]
Hello,

This forum is only intended for reporting issues related to UL for Linux. Please post your questions through the following link.
https://www.mccdaq.com/support/support_form.aspx

Thank you
