### ISSUE TITLE
fpga bitfiles should not be installed in /etc

### ISSUE THREAD

**Issue by d4ddi0** [mccdaq/uldaq#16]
/etc is for systemwide configuration files controled by the end user,
not for read-only data like bitfiles.

I've posted a suggested fix, moving them to /usr/share/uldaq/fpga,
which should be compatible with MacOS, and is similar to where the sigrok project puts them. 

https://github.com/mccdaq/uldaq/pull/15

**Comment by sbazaz** [comment]
I made changes in Version 1.2.0 to compile the FPGA images into the library file and removed the fpga folder. The location of the fpga folder should not become a concern on any operating systems, since the FPGA images have been embedded in the shared object file (libuldaq.so)
