### ISSUE TITLE
ulFlashLed reports "no connection established" error 

### ISSUE THREAD

**Issue by ghost** [mccdaq/uldaq#18]
Hi there, I'm currently developing for the 1608FS-Plus, but I've come across some rather strange errors when using the uldaq library.  In the past I've used wjasper's mcc drivers with the daq just to test it, and I managed to get the LED to flash on command. I'm trying to use the uldaq function ulFlashLed now, but the error ERR_NO_CONNECTION_ESTABLISHED is repeatedly returned. This is despite all the analog input functions returning input data properly. The error is returned regardless of whether I've got the daq connected directly to my raspberry pi or to the pi through a powered usb hub.

**Comment by sbazaz** [comment]
I'm unable to duplicate this issue. Please make sure the ulConnectDaqDevice() function is invoked before calling the ulFlashLed() function
