### ISSUE TITLE
No way to set SYNC pin mode to SLAVE/MASTER without AODevice

### ISSUE THREAD

**Issue by caileighf** [mccdaq/uldaq#20]
The only way to set the sync mode is via the AODevice, AOConfig. If you are using a device without an AO subsystem (Like the USB1608FS-PLUS), you CAN NOT set the sync pin even though the hardware supports it. This is a major logic bug. There needs to be a way to set the sync mode without needing an instance of the AODevice.

**Comment by sbazaz** [comment]
I assume you are using the Python interface. Take a look at the **options** parameter of the **[a_in_scan](https://www.mccdaq.com/PDFs/Manuals/UL-Linux/python/api.html#uldaq.AiDevice.a_in_scan)** method. You need to enable the **PACEROUT** mode for the master device and the **EXTCLOCK** mode for the slave device.
