### ISSUE TITLE
Unclear wording in documentation

### ISSUE THREAD

**Issue by Firionus** [mccdaq/uldaq#22]
# Problem

In the [Python documentation](https://www.mccdaq.com/PDFs/Manuals/UL-Linux/python/api.html#uldaq.AoDevice.a_out_scan) the rate argument of `AoDevice.a_out_scan` is described as "rate (float) – Sample output rate in scans per second."

I found this confusing. I assumed it would describe how often the whole buffer is played back per second. 

# Proposed solution

I propose changing the description to: "Output scan rate in samples per second. For valid range see AoInfo.get_min_scan_rate and AoInfo.get_max_scan_rate. "

Also change return description to "Returns: The actual output scan rate in samples per second."

## Advantages

This brings the units in line with the descriptions for `AoInfo.get_min_scan_rate` and `AoInfo.get_max_scan_rate`. 

By googling I was not able to find a single reference to the unit "scans per second" in the context of outputting signals - only reading ("scanning") data. 

That way it is also clear what values are valid - otherwise one is left wondering why the device will not output at a rate of 5 Hz, even if specified. 

# Other affected documents

The same issue appears in the C documentation.

**Comment by sbazaz** [comment]
Please submit the issues through the MCC technical [support page](https://www.mccdaq.com/support/support_form.aspx)

Thank you
