### ISSUE TITLE
OSError: dlopen(libuldaq.dylib, 6): image not found

### ISSUE THREAD

**Issue by nsabourin** [mccdaq/uldaq#26]
Hi,
I have problems to import uldaq. 
My operating system is. macOs Big sur(intel) with python 2.7 (I cannot use python 3)

I tried to install it with `pip install uldaq`. But, it seams to not work properly when importing.

An example when I'm trying to import it with ipython:
![image](https://user-images.githubusercontent.com/57267176/117677685-ad827080-b17c-11eb-885c-81dac6509892.png)

**Comment by sbazaz** [comment]
I seems the uldaq C library is missing from your system. You need to install the uldaq C library first before you install the python library.  The uldaq python library interfaces the C library. Follow the instructions [here](https://github.com/mccdaq/uldaq) to install the C library first.

**Comment by nsabourin** [comment]
@sbazaz I already installed the uldaq C library. But, I tried to reinstall the library and it still not working :/ It doesn't work with python 3.9 and 2.7

**Comment by clappertown** [comment]
I had similar problem and tried  export LD_LIBRARY_PATH=/usr/local/lib in terminal and then it works.

**Comment by 1IfByLAN2IfByC** [comment]
Running into a similar problem on Mohave, and later Catalina. With Catalina, the error is the same `OSError: dlopen(libuldaq.dylib, 6)` but now the error is explained as `file system relative paths not allowed in hardened programs`

**Comment by sbazaz** [comment]
@nsabourin A new version of the Universal Library Python API  (ver 1.2.3) is posted [here](https://pypi.org/project/uldaq/). Could you please give it a try to see if the changes in that version fix your issue on macOS.
