### ISSUE TITLE
PMD-1208FS support

### ISSUE THREAD

**Issue by iPsych** [mccdaq/uldaq#31]
It seems uldaq cannot detect PMD-1208FS.
Is there any way to add this device?
The device is readable in windows with InstaCal.

**Comment by jeffreyg3** [comment]
That is correct.  here is a link to all the uldaq supported devices:  

https://www.mccdaq.com/PDFs/Manuals/Linux-hw.pdf

No, there is no way to add that device.
You can use 3rd party drivers with the PMD/USB-1208FS:  https://www.mccdaq.com/daq-software/Linux-Support.aspx
However, MCC does not provide any support.
