### ISSUE TITLE
Open source repo for python API and packaging code

### ISSUE THREAD

**Issue by jaustinpage** [mccdaq/uldaq#34]
I see that a a while ago there was a request for open sourcing the python packaging for the uldaq python package. https://github.com/mccdaq/uldaq/issues/13

Sure is a shame that this suggestion has not seen any follow through. 

Here is an example of how this could be beneficial for both MCC and the community of uldaq users:

Right now the python library depends on the c library. But, the python packages do not include built c libraries in the wheel files. Python wheels have the ability to include c libraries compiled against older versions of glibc, producing a wheel file that does not require the end user to download, compile, and install the dependent c libraries. This simplifies installation for people who are ok with using the compiled libraries.

Motivated members of the community might be willing to contribute the knowledge and expertise to produce these manylinux wheels back to MCC if they had a github repo to facilitate the contribution. This would allow mcc and the community to benefit from this streamlined installation process. Win-win.

**Comment by sbazaz** [comment]
Hello,

This forum is only intended for reporting **issues** related to the C Library. Please post your suggestions through the following link.
https://www.mccdaq.com/support/support_form.aspx

Thank you
