### ISSUE TITLE
ulTIn does not return ERR_OPEN_CONNECTION for disconnected thermocouple channels on the USB-2408-2A0

### ISSUE THREAD

**Issue by MarkRivers** [mccdaq/uldaq#36]
On the USB-2408-2A0 on Windows cbTIn returns error=OPENCONNECTION for all channels that do not have thermocouples connected.  On the USB-2408-2A0 Linux ulTIn is not returning ERR_OPEN_CONNECTION for such channels.  ulTIn does correctly return ERR_OPEN_CONNECTION on the E-TC module, for example.

Test conditions for USB-2408-2A0:
- All 8 channels configured for thermocouple input and type K thermocouple.
- First 4 channels being read at 10 Hz.
- Type K thermocouples connected to channels 0 and 1, no connection to channels 2 and 3.

This is the piece of test code on Windows.
```
      status = cbTIn(boardNum_, addr, scale, &fVal, filter);
printf("cbTIn status=%d, addr=%d, scale=%d, fVal=%f, filter=%d\n", status, addr, scale, fVal, filter);
 ```

This is the output for a single cycle of reading all 3 channels:
```
cbTIn status=0, addr=0, scale=0, fVal=22.665619, filter=0
cbTIn status=0, addr=1, scale=0, fVal=22.171738, filter=0
cbTIn status=145, addr=2, scale=0, fVal=-9999.000000, filter=0
cbTIn status=145, addr=3, scale=0, fVal=-9999.000000, filter=0
```
Note that channels 2 and 3 both return status=145, which is OPENCONNECTION in cbw.h.  This is the correct behavior.

This is the piece of test code on Linux:
```
    UlError error = ulTIn(daqDeviceHandle_, Chan, tempScale, flags, &data);
printf("ulTIn error=%d, Chan=%d, tempScale=%d, flags=%d, data=%f\n", error, Chan, tempScale, flags, data);
```

This is the output for a single cycle of reading all 3 channels:
```
ulTIn error=0, Chan=0, tempScale=1, flags=0, data=20.400458
ulTIn error=0, Chan=1, tempScale=1, flags=0, data=21.341698
ulTIn error=0, Chan=2, tempScale=1, flags=0, data=1914.551081
ulTIn error=0, Chan=3, tempScale=1, flags=0, data=-9999.000000
```
Note that error=0 on channels 2 and 3, while it should be ERR_OPEN_CONNECTION.  The data is -9999 on channel 3, but it is some other large value on channel 2.  This can cause confusion, cbTIn should be correctly reporting the open connection status.  The hardware appears capable of this, since it works on Windows.

**Comment by MarkRivers** [comment]
I found that there is an option to enable open thermocouple detection.  I added this to my code and now it detects open thermocouples on the USB-2408-2A0.
```
                // Need to set thermocouple open detection
                error = ulAISetConfig(daqDeviceHandle_, AI_CFG_CHAN_OTD_MODE, DevNum, OTD_ENABLED);
```
It seems strange that this appears to be the default on the E-TC, since I did not enable it explicitly in UL for Linux on that device.
It must also be the default for the USB-2408-2A0 on Windows, since I did not explicitly enable it with BIDETECOPENTC  from cbw.h.

I am no longer having a problem, but I'd like to leave this issue open to allow a chance for the developers to respond to why this seems to be default on some devices and not others?

**Comment by sbazaz** [comment]
On E-TC, the device configurations are stored on EEPROM and UL for Linux reads and applies those settings when it loads. However, the USB-2408-2A0 configuration are not stored on the device and users are responsible for settings the default configurations explicitly when using the UL for Linux.  On windows, InstaCal stores the configurations in the config file and every time the UL for windows loads, it applies those settings automatically. If you have further questions please reach out to MCC through their [tech support form](https://www.mccdaq.com/support/support_form.aspx)

**Comment by MarkRivers** [comment]
> On windows, InstaCal stores the configurations in the config file and every time the UL for windows loads, it applies those settings automatically. 

That is not true in my case, because I am not using InstaCal on Windows.  I have called cbIgnoreInstaCal() at the beginning of my program, and I am using cbGetDaqDeviceInventory to find the device instead.  So there must be some other explanation for the difference in behavior of UL for Linux and UL for Windows on this device.
