### ISSUE TITLE
TC-32 and TC-32 exp

### ISSUE THREAD

**Issue by jeonghanlee** [mccdaq/uldaq#48]
Is there any other way that we can identify automatically to detect a single TC-32 or a TC-32 with the expansion board? 

The code has the hard-coded numbers (32 and 64) inconsistently in some places. In our requirement, we only use 32 channels per model.

https://github.com/mccdaq/uldaq/blob/1d8404159c0fb6d2665461b80acca5bbef5c610a/src/net/ETc32.cpp#L21

https://github.com/mccdaq/uldaq/blob/1d8404159c0fb6d2665461b80acca5bbef5c610a/src/net/ai/AiETc32.h#L60

https://github.com/mccdaq/uldaq/blob/1d8404159c0fb6d2665461b80acca5bbef5c610a/src/net/ai/AiETc32.cpp#L17

https://github.com/mccdaq/uldaq/blob/1d8404159c0fb6d2665461b80acca5bbef5c610a/src/net/ai/AiETc32.cpp#L23

**Comment by sbazaz** [comment]
You can check if an expansion board is attached by calling the ulDevGetConfig function. You need to set the configItem parameter to DEV_CFG_HAS_EXP. [Here](https://www.mccdaq.com/PDFs/Manuals/UL-Linux/c/uldaq_8h.html#a5ea5d07adb1754ffe2b90fa7921a16f4) is the documentation
