### ISSUE TITLE
USB-1608GX drops occasionally drops first sample when run at high frequencies in continuous mode.

### ISSUE THREAD

**Issue by PerrinWaldock** [mccdaq/uldaq#50]
When sampling multiple channels in continuous mode at more than 1kHz, I found that the data is frequently (but not always) offset by one channel. For example, if conducting a scan using 

ul.a_in_scan(0, 3, AiInputMode.DIFFERENTIAL, Range.BIP10VOLTS, 2000, ScanOption.DEFAULTIO | ScanOption.CONTINUOUS, AInScanFlag.DEFAULT, data)

data[0] corresponds to channel 1 and data[3] corresponds to channel 0 most (~60%) of the time. Most of the time, data[0] corresponds to channel 0, and occasionally data[0] corresponds to channel 2.

**Comment by sbazaz** [comment]
Please submit the issues through the MCC technical [support page](https://www.mccdaq.com/support/support_form.aspx)

Thank you
