### ISSUE TITLE
configure is missing from git archive

### ISSUE THREAD

**Issue by patsummit** [mccdaq/uldaq#54]
Configure is in the tar.bz files that can be pulled from github but configure is not in the main branch of the git repository.  So cloning the repository to get the source code produces a directory tree that cannot be build with ./configure && make && make install  
[problem.txt](https://github.com/mccdaq/uldaq/files/11286321/problem.txt)

**Comment by sbazaz** [comment]
If you follow the instructions, we don't mention anywhere that users need to clone the repo. If you have to clone the repo then you need use Autotools to generate the config file from the config.ac which is provided in the repo.
