### ISSUE TITLE
USB-1808 Counter and Encoder issue

### ISSUE THREAD

**Issue by thojDufour** [mccdaq/uldaq#59]
When trying to use both the counter input and the encoder input at the same time, the encoder simply jump from 0 to 1 and back while the counter does not move.
If the encoder and counter are plugged in two separate DAQ devices, everything works as expected.

**Comment by sbazaz** [comment]
Please submit the issues through the MCC technical [support page](https://forum.digilent.com/forum/39-measurement-computing-mcc/)

Thank you
