### ISSUE TITLE
./AOut Example of uldaq not finding Daq device

### ISSUE THREAD

**Issue by jnsville** [mccdaq/uldaq#6]
I followed instructions to install uldaq and libusb. When I run examples, they do not find my installed device.  My installed device is usb-3101. See issue in image below. 
![image](https://user-images.githubusercontent.com/43255512/46841721-87a34e00-cd7e-11e8-890b-91a7387cf8f4.png)

**Comment by jeffreyg3** [comment]
Hi Jerry,
At present, the USB-3100 series is not supported by the uldaq.  For a complete listing of supported devices, please see:  https://www.mccdaq.com/PDFs/Manuals/Linux-hw.pdf
Best regards,
Jeff

**Comment by MCC-AE** [comment]
Note that MCC is adding support for the USB-3101 in the next version, due out in a few weeks.
