### ISSUE TITLE
Using Multiple USB Devices

### ISSUE THREAD

**Issue by Oskee-Wow-Wow** [mccdaq/uldaq#60]
Hello - hopefully a simple question.
I'm using MCC USB-1208FS-Plus and wondering how I would differentiate multiple devices in the uldaq software plugged into the USB so that I can control each individually?   For grins, let's say I wanted to control 4 separate devices.

Thx,
Oskee-Wow-Wow

**Comment by sbazaz** [comment]
The device descriptor has a member called **uniqueId** which is a string that uniquely identifies a specific device. Here is the [spec](https://files.digilent.com/manuals/UL-Linux/c/struct_daq_device_descriptor.html)
