### ISSUE TITLE
Raspberry with Ubuntu22.04 

### ISSUE THREAD

**Issue by yu-mei** [mccdaq/uldaq#62]
Hi MCC support,

I am wondering if this uldaq can be used for my raspberry pi, which is in ubuntu 22.04. Because the daqhats is only supported in rasberry OS, I am trying to check if this can used as alternative one.

Thanks,
Yu

**Comment by sbazaz** [comment]
Refer to the [Prerequisites](https://github.com/mccdaq/uldaq?tab=readme-ov-file#prerequisites) for a list of supported Linux distributions for uldaq.

**Comment by yu-mei** [comment]
Thank you.
