### ISSUE TITLE
Missing 1608FS support

### ISSUE THREAD

**Issue by zougloub** [mccdaq/uldaq#63]
Hi,

The 1608FS-PLUS is supported but not the 1608FS. I'd like to be able to use this library with an 1608FS if possible...

Thank you,

**Comment by FaSoa** [comment]
Hello @zougloub.

Linux support for the USB-1608FS is provided with a third-party driver, not UL for Linux (uldaq).
https://files.digilent.com/manuals/Linux-hw.pdf
https://digilent.com/reference/software/linux-support-for-mccdaq/start

Regards,
Fausto

**Comment by zougloub** [comment]
Thank you for the prompt response @FaSoa. I'll just use https://github.com/wjasper/Linux_Drivers then.
