### ISSUE TITLE
USB1604HS-2AO Compatibility

### ISSUE THREAD

**Issue by rbrenesh** [mccdaq/uldaq#64]
Are there any plans to add compatibility to USB1604HS-2AO? I noticed all the high sampling DAQs (>500kS/s) are not supported by uldaq. Is there some inherent limitation or is it because the C++ drivers haven't been written?

I also noticed that the Windows API seems to have compatibility with the USB1604HS-2AO. Not sure if there's some way I can help out to port it between the two APIs.

**Comment by FaSoa** [comment]
Hello @rbrenesh .
There are no plans to add support for the USB-1604HS Series in UL for Linux (uldaq).

Regards,
Fausto

**Comment by sbazaz** [comment]
FYI, uldaq supports devices with sampling rates exceeding 500kS/s, such as the USB-2020.

**Comment by moconnor-oled** [comment]
@rbrenesh Did you have any luck forking/porting this to Linux? I have the same instrument that I would like to run on a Linux machine. It's the only driver that is keeping me from moving off of Windows for this test stand.
